print("complete name: Johari B. Gandawali ")
print("course: bachelor of science in computer science ")
print("section: CS1D ")
print("age: 20 ")
print(" birthday: DECEMBER 06 2002 ")
print("complete home address: zONE 9 POBLACION LAGUINDINGAN MISAMIS ORIENTAL ")

print("complete name: Johanie A. Abulkhair ")
print("course: bachelor of science in computer science ")
print("section: CS1D ")
print("age: 19 ")
print(" birthday:July 28 2004 ")
print("complete home address: Villa Angela Balulang Cagaan De Oro City ")

print("complete name: Michael Joshua S. Pabellan ")
print("course: bachelor of science in computer science ")
print("section: CS1D ")
print("age: 18 ")
print(" birthday:May 28 2005 ")
print("complete home address: Lawesbra, Lapasan ")